### ISSUE TITLE
Do not allow ESC to open the menu

### ISSUE THREAD

**Issue by MechanicPig** [RedFlames/CollabLobbyUI#3]
After pressing ESC to return from the pause menu, releasing it later will open the menu. I think the problem is caused by the following code. Is this intentional design?
https://github.com/RedFlames/CollabLobbyUI/blob/11854f8e039422109a68babdb1c7f9b2601779d6/Entities/NavMenu.cs#L219-L222

**Comment by RedFlames** [comment]
Huh, yeah that shouldn't be happening. I'm surprised this hasn't been reported to me earlier. Looks like you gotta hold Escape for at least half a second or so.
I'll try turning that `MInput.Keyboard.Released(Keys.Escape)` into a `(IsActive && MInput.Keyboard.Released(Keys.Escape))` or rather lump it in with the other close binding, thanks for already finding the relevant code for me :3
